### ISSUE TITLE
Allow specifying a max amount of images to upload

### ISSUE THREAD

**Issue by tw2113** [christianbayer/image-uploader#1]
Hi.

Would love to see how easy it'd be to set a max amount of images to upload at one time. Hoping to use this plugin for a client and this is a request for the form submission involved.

I've been liking everything else I see thus far, and it's been easy to make use of.

**Comment by christianbayer** [comment]
Hi,

thank you for the suggestion. I'll put this in the roadmap for the next release. If you have any other suggestions for enhancing the plugin, feel free to share them with me!

**Comment by christianbayer** [comment]
Added support to max files in 96fb154a63a1e6208db5577cfca1f9babdc96fb8.
