### ISSUE TITLE
Allowed extensions & Allowed mime types not working

### ISSUE THREAD

**Issue by mxmp210** [christianbayer/image-uploader#27]
> extensions
> 
> Type: array
> 
> Default: ['.jpg', '.jpeg', '.png', '.gif', '.svg']
> 
> Array of strings with the allowed extensions. Enabled by default. To disable this validation, set it as undefined. If the uploaded file does not have one of these extensions, an alert will appear and the image will not be sent.
> mimes
> 
> Type: array
> 
> Default: ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml']
> 
> Array of strings with the allowed mime types. Enabled by default. To disable this validation, set it as undefined. If the uploaded file does not have one of these mime types, an alert will appear and the image will not be sent.

setting them undefined selects default values, instead of ignoring accept and mim arrays.
Only workaround is to set `[]` empty array i.e. 

```
	$('.images').imageUploader({
			imagesInputName: 'photos',
			extensions : [],
			mimes : [],
			maxFiles: 5
	});
```

**Comment by urgido** [comment]
Same issue here.

**Comment by mxmp210** [comment]
> Same issue here.

JS has it's perks, use your own array to define values as shown in example. Empty array for no value and specific types or extensions to cover your usecase.

Although specifying null values would be nice feature to compeltely disable attributes.
