### ISSUE TITLE
How to override the preloaded images.

### ISSUE THREAD

**Issue by maddyBoy** [christianbayer/image-uploader#4]
I show the user the previously submitted images in `preloaded`. So that the user can add new or remove the prev submitted images. But if a user remove preloaded images and submit the form plugin will show still the same old data.

What I am assuming is plugin will save those images which are currently visible to end-user.

Am I missing any settings?

```js
jQuery('.upload-images').imageUploader({
    preloaded: preloadedObj,
    preloadedInputName: 'old',
    imagesInputName: 'upload_log',
    extensions: ['.jpg', '.jpeg', '.png'],
    maxFiles: 5,
    label: 'Upload Logos',
    maxSize: 2 * 1024 * 1024,
});

```

**Comment by christianbayer** [comment]
Hi,
I didn't quite understand the problem.. Let's say you have three images the user uploaded yesterday (preloaded images). Now, if you remove two of them and submit the form, it still showing the three for the user? Did you exclude them on server side, after submitting the form?

**Comment by maddyBoy** [comment]
@christianbayer ,

The problem is solved.I have to manage the two different input fields `preloadedInputName` and `imagesInputName`. 

Thank you.

**Comment by hoangphidev** [comment]
> Hi,
> I didn't quite understand the problem.. Let's say you have three images the user uploaded yesterday (preloaded images). Now, if you remove two of them and submit the form, it still showing the three for the user? Did you exclude them on server side, after submitting the form?

For example, I uploaded 3 photos before then I edited and deleted 2 pictures and added 3 new ones. So after that I have 4 pictures but I have trouble getting the other 1 remaining image. Please help me.
