### ISSUE TITLE
Cannot Submit on Codeigniter

### ISSUE THREAD

**Issue by MGZEVANGELION** [christianbayer/image-uploader#7]
Hi when i tried to implement the script and click on submit, I dont recieve info on my controller with
$data[ 'images' ] = $this->input->post('images');

How i can submit the images on my controller?

**Comment by christianbayer** [comment]
Hi,
can you see them under $_POST?

**Comment by MGZEVANGELION** [comment]
I could already fix the problem, it was an error from my controller. Thanks for the reply.
